### ISSUE TITLE
Spurious inference of Dict[str, Dict[str, Union[dict, str]]]

### ISSUE THREAD

**Issue by kerneis-anssi** [google/pytype#1007]
I get many errors trying to run pytype on the following file: https://github.com/chipsec/chipsec/blob/master/chipsec/chipset.py#L386

For instance:
```
File "chipsec/chipsec/chipset.py", line 386, in init_xml_configuration: No attribute 'lower' on Dict[str, Dict[str, Union[dict, str]]] [attribute-error]
  In Union[Dict[str, Dict[str, Union[dict, str]]], str]
```

After some refactoring and `reveal_type` experiments, I've managed to identify what these errors have in common: pytype infers that the values in the dictionary [xml.etree.ElementTree.Element.attrib](https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.attrib) have either type `str` (which is correct) or some strange dict type, such as `Dict[str, Dict[str, Union[dict, str]]]` (which makes no sense).

I have no idea where this error comes from. `attrib` is correctly annotated in typeshed: https://github.com/python/typeshed/blob/master/stdlib/xml/etree/ElementTree.pyi#L65

Trying to reduce the example to a minimal version, pytype raises no error:
```
import xml.etree.ElementTree as ET

tree = ET.parse("/tmp/test.xml")
root = tree.getroot()
for _cfg in root.iter('configuration'):
    if 'platform' not in _cfg.attrib:
        continue
    platform = _cfg.attrib['platform'].upper()
    if platform.startswith('pch'):
        print(_cfg.attrib['platform'])
```

**Comment by rchen152** [comment]
That's indeed an odd error. This kind of weirdness often occurs with heterogeneous dictionaries (for which our recommendation is to annotate the dictionary as `Dict[<KeyType>, Any]`), but it doesn't look the code ever modifies `_cfg.attrib`.

**Comment by rchen152** [comment]
I suspect what's happening is that this line:
```
_register.attrib['FIELDS'] = reg_fields
```
(https://github.com/chipsec/chipsec/blob/b2a61684826dc8b9f622a844a40efea579cd7e7d/chipsec/chipset.py#L580) causes pytype to think that the type of `Element.attrib` may have been modified.

**Comment by rchen152** [comment]
Yup, the majority of the type errors disappear if I comment out that line.

**Comment by rchen152** [comment]
I don't think there's much we can do to fix this in pytype. For all pytype knows, `attrib` is a class attribute, not an instance attribute (stubs don't consistently mark class attributes specially), so it may be shared among all `Element` instances. We could perhaps determine that only the value of the `FIELDS` key can be a dict and the others are all still strings, but pytype doesn't yet support typing.TypedDict, and regardless, `attrib` is annotated as a regular dict.

On your end, any of the following workarounds should work:
* Set `_register.attrib['FIELDS']` to a str rather than a dict.
* Annotate `reg_fields` as `Any`:
  ```
  from typing import Any
  ...
  reg_fields: Any = {}
  ```
* Cast `reg_fields` to `str` (this is a lie, but it'll prevent pytype from modifying the value type of `attrib`):
  ```
  import typing
  ...
  _register.attrib['FIELDS'] = typing.cast(str, reg_fields)
  ```

**Comment by kerneis-anssi** [comment]
Thanks a lot for investigating, that's extremely useful!
