### ISSUE TITLE
Consistently getting [import-error] when using PYTHONPATH

### ISSUE THREAD

**Issue by nirradi** [google/pytype#1025]
directory structure: 
```
/app/src
/app/src/bridge.py
/app/src/writers/bridge_metrics.py
```

running like 
```
PYTHONPATH=./src pytype ./src
```

and bridge_writer.py

```
import bridge
```

getting the error
```
FAILED: /app/src/.pytype/pyi/src/writers/bridge_metrics.pyi 
/usr/local/bin/python -m pytype.single --imports_info /app/src/.pytype/imports/src.writers.bridge_metrics.imports --module-name src.writers.bridge_metrics -V 3.9 -o /app/src/.pytype/pyi/src/writers/bridge_metrics.pyi --analyze-annotated --nofail --quick /app/src/writers/bridge_metrics.py
```

**Comment by rchen152** [comment]
Now that I'm looking at this more carefully, I think the problem here is that setting the `PYTHONPATH` environment variable isn't the right way to tell pytype where source directories are. They should be passed in via pytype's `--pythonpath` flag (https://github.com/google/pytype/blob/9a0f492875f8440627fef7de42ee9244e89e8a06/pytype/tools/analyze_project/config.py#L54-L56).
