### ISSUE TITLE
Incorrect [invalid-function-type-comment] for unconditional early return

### ISSUE THREAD

**Issue by Cebtenzzre** [google/pytype#1082]
#### Software versions
Python 3.9.7
pytype 2021.12.08

#### Testcase
```python
def foo():
    if True:
        return
    x: list[int] = []
```

#### Description
There are no comments in this example. Yet pytype reports that the variable annotation is an invalid function type comment:
```
$ pytype-single repr.py
File "repr.py", line 1, in <module>: Invalid function type comment: list[int] [invalid-function-type-comment]

For more details, see https://google.github.io/pytype/errors.html#invalid-function-type-comment
```

This easily becomes a [redundant-function-type-comment] error if the function is annotated (`def foo() -> None:`). No error is reported if any code is put before the if statement, or if `True` is replaced with a truthy variable.

**Comment by rchen152** [comment]
What's happening is that pytype looks for a `STORE_*` opcode to attach the `list[int]` annotation to. But because `if True: return` is always executed, the rest of the function body is optimized away before pytype even sees it, so it can't find such an opcode. So it assumes that the annotation must belong to the function signature. I guess we might be able to fix this by discarding type annotations that occur on lines that don't appear in the bytecode? This seems like a pretty unusual edge case, though.

**Comment by Cebtenzzre** [comment]
For what it's worth, I only saw this while trying to minimize other code that pytype fails on. It's a confusing error message but it's no big deal if this gets closed as WONTFIX.

**Comment by rchen152** [comment]
This no longer produces an [invalid-function-type-comment] error. pytype completes successfully, albeit with a `ERROR:pytype.directors No STORE_* opcode found for annotation _VariableAnnotation(start_line=4, end_line=4, annotation='list[int]') on line 4` log statement. This seems like a pretty reasonable and informative way to handle this case, so closing.
