### ISSUE TITLE
Please consider updating typing-extensions to 4.1.1

### ISSUE THREAD

**Issue by NeilGirdhar** [google/pytype#1135]
It would be nice to use `dataclass_transforms` from typing-annotations 4.1.0 [here](https://github.com/google/flax/pull/1927), but it appears that it's not exported yet [here](https://github.com/google/pytype/blob/main/pytype/overlays/typing_extensions_overlay.py).

**Comment by NeilGirdhar** [comment]
Thank you for the quick turnaround!

**Comment by NeilGirdhar** [comment]
Sorry, I think I'm not explaining myself well.  Previously, pytype supported defining `__dataclass_transforms__` [like so](https://github.com/google/flax/blob/main/flax/struct.py#L34), and when this was applied, it recognized the target as a dataclass?  Maybe I've misunderstood something.

**Comment by rchen152** [comment]
I'm fairly certain we've never supported `__dataclass_transforms__`. Any chance you're thinking of [https://github.com/microsoft/pyright](https://github.com/microsoft/pyright)? (The names are rather too similar, now that I think about it.)

**Comment by NeilGirdhar** [comment]
@rchen152 Okay, yes, I hadn't actually tested whether pytype supports it.  I got [these strange errors](https://github.com/google/flax/pull/1927#issuecomment-1052107383) when I swapped the old `__dataclass_transforms__` for the one in `typing_extensions`. I guessed that you supported one construction and not the other.

Okay, so I wonder why my small pull request causes the errors?

**Comment by rchen152** [comment]
Oh interesting. That error looks like it's occuring because pytype has some native `flax` support in the form of an [overlay](https://github.com/google/pytype/blob/main/pytype/overlays/flax_overlay.py), which assumes that `Module` is a class. Since pytype doesn't know what the `dataclass_transform` decorator does, the addition of the decorator turns `Module` into an `Any` type (from pytype's perspective), breaking that assumption.

`typing_extensions.pyi` does define `dataclass_transform` as returning an identity function, but we don't seem to be using that. Let me see if I can change that.

**Comment by NeilGirdhar** [comment]
@rchen152 Thanks a lot!
