### ISSUE TITLE
Using TypeVar converts the type of a TypedDict to just Dict.

### ISSUE THREAD

**Issue by theahura** [google/pytype#1180]
Is there a way to do something like this:
```python
class Animal(typing.TypedDict):
  name: str

class Cow(Animal):
  name: "Cow"
```
Right now this results in `Duplicate TypedDict key name in classes Animal and Cow`, which is technically true, but Cow is only adding specificity to Animal and not actually changing the type. 

Somewhat similar problem. How do I avoid something like this:
```python
def generic_foo(in: Animal) -> Animal:
  return in

cow: Cow = {'name': 'Cow'}
cow = generic_foo(cow)  # type is now 'Animal'
```
In both cases it seems like the type checker isnt 'smart' enough to recognize that the data is the same type, just more/less specific.

Thanks in advance!

**Comment by rchen152** [comment]
For the first issue, simply have both `Animal` and `Cow` inherit from `TypedDict` directly; i.e., don't try to make `Cow` a nominal subclass of `Animal`:
```
from typing import Literal, TypedDict

class Animal(TypedDict):
  name: str

class Cow(TypedDict):
  name: Literal["Cow"]
```
You should then be able to pass in a `Cow` everywhere an `Animal` is expected. For the second issue, you should be able to use TypeVar to preserve the input type:
```
from typing import TypeVar
T = TypeVar('T', bound=Animal)
def generic_foo(in: T) -> T:
  return in
```
Unfortunately, pytype seems to have a bug where it decides that `generic_foo(cow)` is a `dict` rather than the more specific `Cow`.

**Comment by theahura** [comment]
Thanks for the help on both counts. I was hoping the former would be able to keep the inheritance structure, because I wanted to ensure that the type `Cow` had the rest of the fields relevant to `Animal` as part of the type checking. Otherwise though this was sufficient for me to resolve my issues!
