### ISSUE TITLE
Question: merge two `pyi` files

### ISSUE THREAD

**Issue by mrkeuz** [google/pytype#1216]
Hello, found existing of `merge_pyi` tool for merging `pyi` types into `py` files.

### Use case: 
I want to merge two `pyi` files. Purpose is generating stubs for code i.e. via [mypy.stubgen](https://mypy.readthedocs.io/en/stable/stubgen.html) and next apply some clarifications for types from external file. Add doc strings, clarify return parameters manually and so on. 

My use case is support stub package for some external lib. And when API is changed during release just regenerate stubs, but save all  previously collected type knowledge. In this case we can automate entire process of generating and testing stubs correctness (i.e. via [mypy.stubtest](https://mypy.readthedocs.io/en/stable/stubtest.html)). 

### Question:
Are there any tools for merging exactly `pyi` files? Or there is only one way is parse `pyi` manually and manipulating parse tree from script?

Thanks in advance!

**Comment by martindemello** [comment]
that's an interesting use case. i believe `merge_pyi` should be able to handle it, since pyi files are syntactically python (though we don't handle doc strings, just param and return types). run a few experiments with passing two pyi files to `merge_pyi`, and see if it does what you need. if there are any blocking issues file bugs for them and we will take a look.

**Comment by mrkeuz** [comment]
I've tried to merge `pyi`'s with `merge_pyi` but unfortunately nothing happened. Literally, it does not show any diff. 

As I understand from sources of a `libcst`, it expected exactly `py` files in their [visitor](https://github.com/Instagram/LibCST/blob/5992a7d83d234e7575ad81107d352846ff1abb37/libcst/codemod/visitors/_apply_type_annotations.py) and somehow forced this (i'm not familiar with `libcst`) and don't know how easily fix this. 

Will try to dive into the code when it's time. But so far I don't really understand how it all works. Pettern visitor is new to me.

**Comment by martindemello** [comment]
can you share your test files? i tried it out with a small example and it seems to work:
```
$ cat a.pyi 
def f(x: int): ...
$ cat b.pyi 
def f(x) -> int: ...
]$ merge-pyi --diff a.pyi b.pyi
- def f(x: int): ...
+ def f(x: int) -> int: ...
?              +++++++
```

**Comment by mrkeuz** [comment]
Wow, thanks!

It's working. I understand my fault. I've tried complex example at start. With classes.
But on corned cases it still does not work:

- already defined types
- classes (even with empty return definitions)


See example:

- a.pyi
  ```python3
  from typing import Any

  class A:
      def read(): ...
  
  def func_1(a: Any) -> Any: ...
  
  ```
- b.pyi
  ```python3
  class A:
      def read(a: int) -> str: ...
  
  def func_1(b: int) -> str: ...
  ```
Diff give nothing. (((

**Comment by mrkeuz** [comment]
UPD: Found `overwrite_existing_annotations` parameter in `libcst` visitor. Will try to change now.

**Comment by martindemello** [comment]
the issue here isn't the pyi file, it is that `merge_pyi` deliberately will not merge functions with different arity, since they are considered not the same function. if you change the definition in `a.pyi` to `def read(a)` it will merge in the signature in from `b.pyi`.

the second problem can indeed be considered a missing feature - since the definition of `f()` already has type annotations, they will not be overwritten by the annotations from `b.pyi`. there are two things we can do here - firstly, add a flag to expose the overwrite feature (it's already there in libcst), and secondly add a new feature to libcst to only overwrite annotations if they are `Any`, which is arguably a useful behaviour.

**Comment by martindemello** [comment]
will close this bug in favour of #1219.

**Comment by mrkeuz** [comment]
Thank you very much! 

Yes `def read(a)` working now. And `overwrite_existing_annotations` helps to apply annotations even it is already exist.

Many, many thanks for helping! 🚀🚀🚀
Will continue my experiments.

**Comment by mrkeuz** [comment]
Last question. As I understand correctly that you should NOT expect that the merging dostring's will work. 

Here you really need to refine `libcst` visitor?

**Comment by martindemello** [comment]
yes, the libcst visitor deals purely with type annotations, and does not consider docstrings at all. it's definitely a reasonable feature request for `merge-pyi`, but how i would implement it is by writing a new "merge docstrings" libcst visitor and running that as a separate pass, rather than modifying the type annotation visitor. (simply because docstrings have nothing to do with type annotations)

**Comment by mrkeuz** [comment]
Reasonable. Separate visitor will be even simple, I think. Thanks!

Should we create feature request for this?
