### ISSUE TITLE
change using circular imports between `ctypes/__init__.pyi` and `_ctypes.pyi` in `typeshed` crashes `pytype` testing on CI

### ISSUE THREAD

**Issue by junkmd** [google/pytype#1281]
In `typeshed` repository, I am trying to write type stubs as close as possible to the implementation, so I migrated some stuffs from `stdlib/ctypes/__init__.pyi` to `stdlib/_ctypes.pyi`.
And I used circular imports for annotations.

But `pytype` testing on CI was failed.

See python/typeshed#8643.

Are there any plans for fixes?

**Comment by rchen152** [comment]
I'll take a look.

**Comment by rchen152** [comment]
This is luckily an easy fix. The issue is that pytype has its own `_ctypes` stub, because it didn't exist in typeshed. I'll copy over the `RTLD_GLOBAL` and `RTLD_LOCAL` constants for now. Once we've updated pytype's typeshed pin in a few weeks, I'll be able to delete our copy of `_ctypes` altogether.

**Comment by junkmd** [comment]
@rchen152 
Thank you for response.

As soon as I confirm this fix completed, I will make the changes to `typeshed`.
