### ISSUE TITLE
Will this library not be updated in the future? 

### ISSUE THREAD

**Issue by wannch** [google/pytype#1622]

**Comment by frigus02** [comment]
Hi. I'm a new member on the Python team at Google. I assume you're asking because of the recent news, e.g. https://news.ycombinator.com/item?id=40171125.

We will continue to maintain and update pytype. pytype is still used and relied on heavily at Google.

However, updates as well as responses to issues are likely a bit slower for a bit, while the new team members are getting up to speed.

**Comment by laike9m** [comment]
Learn Python the Hard Way

**Comment by frigus02** [comment]
I'm going to close this issue. I hope recent activity on the repo shows that progress might be a little slow, but it's definitely not abandoned.
