### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by anarkiwi** [google/pytype#181]
Hello!

We really like pytype and use it in our CI environment. Unfortunately for our project it can use a lot of RAM (in this case 900M, but sometimes over 1.2G).

Is there anything we can do to reduce this?

josh@numbers:~/tmp$ git clone https://github.com/faucetsdn/faucet
Cloning into 'faucet'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 32576 (delta 10), reused 13 (delta 5), pack-reused 32548
Receiving objects: 100% (32576/32576), 26.80 MiB | 35.22 MiB/s, done.
Resolving deltas: 100% (21207/21207), done.
josh@numbers:~$ lsb_release -d
Description:    Debian GNU/Linux 9.5 (stretch)
josh@numbers:~$ python3 --version
Python 3.5.3
josh@numbers:~/tmp$ pytype --version
2018.9.26
josh@numbers:~/tmp/faucet$ /usr/bin/time --verbose pytype -V3.5 tests/unit/faucet/test_valve.py 
Analyzing 1 sources with 275 dependencies
        Command being timed: "pytype -V3.5 tests/unit/faucet/test_valve.py"
        User time (seconds): 150.96
        System time (seconds): 6.18
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 2:38.45
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): **901324**
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 1260521
        Voluntary context switches: 361
        Involuntary context switches: 5513
        Swaps: 0
        File system inputs: 0
        File system outputs: 3592
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0

**Comment by rchen152** [comment]
Oof, that's a lot. I'll take a look. At a guess, test_valve.py is pretty large (2306 lines), so splitting it up may help.

**Comment by rchen152** [comment]
I checked out our memory usage, and there doesn't seem to be anything out-of-line about our per-file behavior. Pytype is doing full-blown analysis of 35 files.  About 36% of its memory consumption is due to four files (faucet/valve_route.py, faucet/valve.py, faucet/dp.py, tests/unit/faucet/test_valve.py), but they also represent 46% of the total file size.

I think the only thing we can do here is decrease the number of files we analyze by implementing https://github.com/google/pytype/issues/173. Afterwards, pytype should use~50MB per file changed between runs (or up to a couple hundred if a really large file is touched). Given this, I'm closing this bug in favor of that one.
