### ISSUE TITLE
Over approximation 

### ISSUE THREAD

**Issue by barmakoWS** [google/pytype#226]
I tried to evaluate pytype with the following code example:

    class Banana:
    
        def eat(self):
            return self
    
    
    class Person:
    
        def __init__(self):
            self.no_bananas()
    
        def no_bananas(self):
            self.bananas = []
    
        def add_banana(self, banana):
            self.bananas.append(banana)
    
        def eat_bananas(self):
            bananas = [banana.eat() for banana in self.bananas]
            self.no_bananas()
            return bananas
    
    
    def main():
        person = Person()
        for a in range(1, 10):
            person.add_banana(Banana())
        return person.eat_bananas()

The resulting pyi file (after invoking pytype without any custom option, e.g. `pytype example.py`)

    from typing import Any, TypeVar
    
    _TBanana = TypeVar('_TBanana', bound=Banana)
    
    class Banana:
        def eat(self: _TBanana) -> _TBanana: ...
    
    class Person:
        bananas: list
        def __init__(self) -> None: ...
        def add_banana(self, banana) -> None: ...
        def eat_bananas(self) -> list: ...
        def no_bananas(self) -> None: ...
    
    
    def main() -> Any: ...

The main method's return type is inferred into Any, while it can be resolved into List[Banana]
This seems to be an over-approximation.

Is this result expected from pytype? is it a bug?
Perhaps I'm just not using pytype correctly?

**Comment by rchen152** [comment]
pytype runs in a quick mode that limits the depth to which it'll follow call chains. If you run the single-file tool over the code as `pytype-single example.py -V2.7 -o -`*, it'll do full-blown inference and show a return type of `List[Banana]` as expected. The non-quick mode isn't available in the regular pytype tool yet; if that's something you'd find useful, I can expose it.

\* Why `-V2.7`? It looks like there's a bug in the Python 3 inference that causes the return type to be `list` rather than `List[Banana]`, which I'll have to look into further.

**Comment by rchen152** [comment]
As it turns out, the Python 3 bytecode pushes an extra `<listcomp>` function onto the stack, making the call chain just a little too long for pytype to follow completely. We'd eventually like to increase pytype's maximum depth, but until that happens, I don't think there's anything actionable in this specific case, so I'm going to close this bug.
