### ISSUE TITLE
Add setuptools integration

### ISSUE THREAD

**Issue by grzesuav** [google/pytype#311]
Add integration with https://setuptools.readthedocs.io/, possibly in analog way as in https://github.com/johnnoone/setuptools-pylint

Pros : 
* simpler setup (I can add one build dependency in setup.py and I am able to invoke `python setup.py pytype` )

Cons:
* would make sense to be in separate repository/ as separate python package

**Comment by rchen152** [comment]
That's an interesting idea, thanks!

**Comment by pganssle** [comment]
Just as a word of warning, `setuptools` is trying to move away from having people invoke `setup.py` *at all*. It can cause problems with dependencies. In this situation, we would probably recommend instead that you set up a `tox` environment that invokes `pytype` rather than a `setup.py pytype` command.

**Comment by rchen152** [comment]
Thanks for the information. It sounds like this issue should be closed then, but @grzesuav feel free reopen it if you find something we can do to make using pytype with `tox` easier.

**Comment by grzesuav** [comment]
Wasn't aware of that, thanks :)
