### ISSUE TITLE
attribute-error for importlib.abc.Loader.exec_module

### ISSUE THREAD

**Issue by dseomn** [google/pytype#319]
From https://travis-ci.org/dseomn/dotfiles/jobs/534215443
```
...
File "/home/travis/build/dseomn/dotfiles/.local/lib/python3/site-packages/snipphthalate/plugin.py", line 78, in __init__: No attribute 'exec_module' on _importlib_modulespec._Loader [attribute-error]
  In Union[Any, _importlib_modulespec._Loader]
...
```

The code with the error is the last line of:
```python
    spec = importlib.util.spec_from_file_location('<snipphthalate_plugin>',
                                                  filename)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
```

Documentation for the function is at https://docs.python.org/3/library/importlib.html#importlib.abc.Loader.exec_module

**Comment by rchen152** [comment]
The error is caused by this line: https://github.com/python/typeshed/blob/07d4938251b5f1eda9cb6903bd8754f4cf39865c/stdlib/3/_importlib_modulespec.pyi#L15, where the type of `ModuleSpec.loader` is set to a `_Loader` protocol with only a load_module method. Based on https://github.com/python/typeshed/pull/2626, it appears that the type was intentionally changed from importlib.abc.Loader to a custom protocol because the former was sometimes wrong.

So I'm tempted to say this behavior is working as intended, unless it's documented somewhere that there are cases in which ModuleSpec.loader is guaranteed to be an importlib.abc.Loader rather than any object that implements load_module.

**Comment by dseomn** [comment]
Sounds good. Looking at the importlib documentation again, I think you're right that this is WAI.
