### ISSUE TITLE
Variable type annotations are being ignored

### ISSUE THREAD

**Issue by lkgarrison** [google/pytype#323]
## Sample file:

```
bad_type_var: int = "foo"
```

## Expected result
Expected pytype to tell me that this line contains an error (i.e. `bad_type_var` should was expected to be type "int" but a string was assigned)

*Mypy* gives the expected error: `test.py:1: error: Incompatible types in assignment (expression has type "str", variable has type "int")`

## Actual result
Running `pytype sample.py` results in "Success: no errors found"

## Setup
My setup.cfg specifies python 3.7

`pytype --version` is "2019.05.15"

## Additional information
Other type checking does seem to work, such as wrong-arg checks:

```
def foo(bar: int) -> str:
    return "foo"

my_foo: bool = foo("a string")
```

Running pytype on this file, I get the following error:
```
foo was called with the wrong arguments [wrong-arg-types]
  Expected: (bar: int)
  Actually passed: (bar: str)
```

However, I expected to also see an error that my_foo is annotated as type "bool" but is being assigned a string

Please let me know if this could somehow be a configuration issue on my end

**Comment by rchen152** [comment]
Ah, the problem here isn't that variable annotations are ignored; it's that they're blindly applied. (If you call `reveal_type(bad_type_var)` after your first example, you'll see that the type is `int`, not `str`.) Making sure that such annotations are type-checked against the actual assigned value has been on our TODO list for a while. We haven't had time to do it yet because it requires also fixing up all user code that relies on our current more lenient behavior.

**Comment by rchen152** [comment]
The `--check-variable-types` flag can be used to check variable type annotations now. (We eventually plan to enable this behavior by default.)
