### ISSUE TITLE
"No attribute 'Pattern' on module 're'" reported incorrectly

### ISSUE THREAD

**Issue by adsr303** [google/pytype#386]
This gets reported even though the definition of `Pattern` can be found in `re.py`.

* pytype-2019.8.9
* Python 3.7.4

Example file that fails this check: https://github.com/adsr303/awking/blob/master/awking.py

**Comment by rchen152** [comment]
Looks like an undocumented `Pattern` class was added to the source in 3.7: https://github.com/python/cpython/blob/37fd9f73e2fa439554977cfba427bf94c1fedb6b/Lib/re.py#L262. Typeshed's policy does allow undocumented attributes to be added to type stubs on an as-needed basis, so the fix is to add the class to this file: https://github.com/python/typeshed/blob/master/stdlib/3/re.pyi.

**Comment by adsr303** [comment]
`Pattern` has been present in `re.pyi` since 2015.

**Comment by rchen152** [comment]
pytype seems to recognize re.Pattern now; I tried
```
import re
print(re.Pattern)
```
so closing this issue.
