### ISSUE TITLE
Import error when using `from X import Y`

### ISSUE THREAD

**Issue by AdamGleave** [google/pytype#455]
I'm finding that `pytype` is unable to find an import when using `from X import Y`, but can resolve this fine if `import X` is executed first.

So far I've only observed this with `mpi4py`.

Steps to reproduce:

```
virtualenv -p python3.7 venv
. ./venv/bin/activate
pip install pytype mpi4py
echo "import mpi4py" > test1.py
echo "from mpi4py import MPI" > test2.py
cat test1.py test2.py >> test3.py
cat test2.py test1.py >> test3.py
```

Running:
```
$ pytype test2.py
Computing dependencies                                                                                                                                                       
Analyzing 1 sources with 0 local dependencies                                                                                                                                
ninja: Entering directory `/home/adam/dev/pytype-bug/.pytype'                                                                                                                
[1/1] check test2
FAILED: /home/adam/dev/pytype-bug/.pytype/pyi/test2.pyi 
pytype-single --imports_info /home/adam/dev/pytype-bug/.pytype/imports/test2.imports --module-name test2 -V 3.7 -o /home/adam/dev/pytype-bug/.pytype/pyi/test2.pyi --analyze-annotated --nofail --quick /home/adam/dev/pytype-bug/test2.py
File "/home/adam/dev/pytype-bug/test2.py", line 1, in <module>: Can't find module 'mpi4py'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error.
ninja: build stopped: subcommand failed.
```

But running `pytype` on `test1.py`, `test3.py` and `test4.py` succeeds.

**Comment by rchen152** [comment]
Thanks for the detailed repro instructions! I successfully reproduced the bug (after `apt-get install libopenmpi-dev` to get the mpi headers so mpi4py would install). Looking at the build artifacts, `.pytype/imports/test1.imports` contains an entry `for mpi4py/__init__`, but test2.imports does not, so this seems to be a problem with how .imports is generated.

**Comment by bicobus** [comment]
I have observed the same behavior with PyQt5, not doing a `import PyQt5` will lead to import errors.

Does it apply to all C/C++ python wrappers?

**Comment by rchen152** [comment]
Hmm, I didn't realize mpi4py was a C/C++ wrapper, but it's certainly possible that has something to do with the issue, if it confuses the import finder (https://github.com/google/importlab/blob/master/importlab/import_finder.py) in some way.

**Comment by bicobus** [comment]
Using a test.py file with just the line
```python
from PyQt5 import QtWidgets
```

Where `$PATH` is the path of the virtual environment.

Running:
```
$ python $PATH/lib/python3.7/site-packages/importlab/import_finder.py test.py 
```
Outputs:
```json
[
    ["PyQt5.QtWidgets", "QtWidgets", true, false, "$PATH/lib/python3.7/site-packages/PyQt5/QtWidgets.so"]
]
```

With a test file containing the two lines:
```python
import PyQt5
from PyQt5 import QtWidgets
```

import_finders returns:
```json
[
    ["PyQt5", null, false, false, "$PATH/lib/python3.7/site-packages/PyQt5/__init__.py"],
    ["PyQt5.QtWidgets", "QtWidgets", true, false, "$PATH/lib/python3.7/site-packages/PyQt5/QtWidgets.so"]
]
```

I don't know the output you expect using `importlab.import_finder.get_imports`. These results seems sensible.

**Comment by rchen152** [comment]
Yeah, the import_finder output looks reasonable. Thanks for looking into that. I poked around a bit more, and I think the problem is this line: https://github.com/google/importlab/blob/87d191cacc05cf4fe80a3dd6df461a5b5fc8bba5/importlab/graph.py#L244.
It skips .so files (which is what mpi4py.MPI and presumably PyQt5.QtWidgets are), so even though the right dependency is found, it never gets added to the dependency graph.

**Comment by bicobus** [comment]
Presumably because they are not python files.

Skipping stuff shouldn't be the job of importlab unless asked explicitly. In this case it appears to be the job of pytype to either accept or disregard a dependency. I assume that pytype cannot do anything with object files, and instead would need to rely on stubs if present. Should importlab try to detect the presence of stub files if the found dependency isn't a python file? Should importlab, or pytype, be told where to find said stub files through a cli option? Or should pytype simply ignore wrappers and defaults to `Any` type? Although these questions might be beyond the scope of this issue.

Other wrappers (than MPI4py), such as PySide2 to stay with Qt5, does distribute python stub files alongside the object files while. PyQt5 does not, however they can be generated using [sip](https://www.riverbankcomputing.com/static/Docs/sip/command_line_tools.html#cmdoption-sip-build-pep484-pyi). Static analysis seems to be somewhat of an issue with [PySide2 and mypy](https://bugreports.qt.io/browse/PYSIDE-1100), an interesting discussion to read.

**Comment by rchen152** [comment]
The importlab bug (skipping .so files) has been fixed, so this should work now. pytype won't require the importlab version with the fix until its next release, but you can pick it up now by upgrading to importlab-0.6.1.
