### ISSUE TITLE
Really long / unterminating analysis on bm_regex_v8.py

### ISSUE THREAD

**Issue by rmonat** [google/pytype#484]
I've tried running pytype on a file from the pyperformance benchmarks : 
https://github.com/python/pyperformance/blob/master/pyperformance/benchmarks/bm_regex_v8.py

I've also tried running pytype on the same file with the six and pyperf dependencies removed, but in any case the analysis is very long (I killed it after 1h, I'm using an i7-8650U and enough ram), which in my experience is unusual for pytype.

I'm trying to compare pytype with a tool I'm developing and would be happy to know if that is a normal behavior (I don't really understand how the analysis works / if it uses typeshed annotations for the re module for example) or if it's a bug in that particular case.

Version: 
```
$ pytype --version
2019.12.17
```

**Comment by rchen152** [comment]
pytype running for 1h+ on one file is definitely a bug. We've seen poor performance on large dictionaries before, so my guess is that the `compiled_regex_strings` and `strings` lists are the issue.

pytype uses typeshed stubs when they are available and otherwise treats most external modules as `def __getattr__(name) -> Any`.

**Comment by rmonat** [comment]
Thank you!

**Comment by rchen152** [comment]
I'm going to close this issue, since there isn't anything actionable for us to do regarding this specific file, but we are working on improving pytype's performance on large containers.

In general, https://google.github.io/pytype/faq.html#why-is-pytype-taking-so-long contains some tips for what to do if pytype is taking a long time.
