### ISSUE TITLE
`pytype` breaks when importing from `tensorflow`

### ISSUE THREAD

**Issue by AdamHillier** [google/pytype#504]
As a small, cut-down example, if I run `pytype` on the following Python script:

```python
from tensorflow import keras
from tensorflow.keras.optimizers.schedules import PolynomialDecay

print(PolynomialDecay(1e-4, 5 * 10, end_learning_rate=0, power=1.0))
print(keras.models.Sequential())
```

it reports the error:

 `... in <module>: No attribute 'models' on module 'tensorflow.keras' [module-attr]`.

but the script successfully runs and prints the two objects as expected.

**Comment by rchen152** [comment]
Assigning to me for triage.

**Comment by rchen152** [comment]
Well. What's happening is that pytype generates an import path for tensorflow.keras.optimizers.schedules.PolynomialDecay, and since tensorflow.keras is an intermediate directory in that path, it gets set to os.devnull: https://github.com/google/pytype/blob/baab89445d667952051ab30c5504e5c455941b03/pytype/imports_map_loader.py#L109.

Later, pytype.load_pytd attempts to read the pyi file from /dev/null and gets an empty string, which it interprets as an empty module with no attributes.

We might be able to fix this by setting intermediate directories to the default pyi (all attributes map to Any) rather than /dev/null, but we'd have to first make sure that doing so doesn't hide real attribute errors.

**Comment by rchen152** [comment]
pytype no longer reports any error for the example code, so closing this issue.

**Comment by bioothod** [comment]
Very similar error happens with this code:
```
from tensorflow import keras
from tensorflow.keras.optimizers.schedules import PolynomialDecay

print(PolynomialDecay(1e-4, 5 * 10, end_learning_rate=0, power=1.0))
print(keras.models.Sequential())

**Comment by bioothod** [comment]
```
Computing dependencies
2021-03-12 16:11:49.842449: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-03-12 16:11:49.842473: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/home/zbr/awork/rl/world_model/.pytype'
[1/1] check xxx
FAILED: /home/zbr/awork/rl/world_model/.pytype/pyi/xxx.pyi 
/usr/bin/python3 -m pytype.single --imports_info /home/zbr/awork/rl/world_model/.pytype/imports/xxx.imports --module-name xxx -V 3.8 -o /home/zbr/awork/rl/world_model/.pytype/pyi/xxx.pyi --analyze-annotated --nofail --quick /home/zbr/awork/rl/world_model/xxx.py
File "/home/zbr/awork/rl/world_model/xxx.py", line 4, in <module>: No attribute 'Model' on module 'tensorflow.keras' [module-attr]
```

If you comment `from tensorflow.keras.mixed_precision.experimental import mixed_precision` out, pytype works as expected.

```

Should I fill a new bug for this?
