### ISSUE TITLE
Stray 'nothing' type for empty tuple inference

### ISSUE THREAD

**Issue by brunokim** [google/pytype#549]
While using `merge-pyi -i`, an unannotated function that returns an empty tuple got as type `Tuple[nothing, ...]`. Since this type is not defined, a later pytype run fails. If the function is already annotated, nothing happens.

### Input file:

```
from typing import Tuple

def empty_tuple1():
  return ()

def empty_tuple2() -> Tuple:
  return ()
```

### Output pyi
```
# (generated with --quick)

from typing import Tuple

def empty_tuple1() -> Tuple[nothing, ...]: ...
def empty_tuple2() -> tuple: ...
```

**Comment by rchen152** [comment]
Oops, we should type an empty tuple as `Tuple[()]`.

**Comment by souravbadami** [comment]
@rchen152 - I would like to work on this.

**Comment by rchen152** [comment]
Go for it! Probably the most reasonable fix would be to change PrintVisitor (https://github.com/google/pytype/blob/804fa97e7f9208df2711976085a96f756b3949e6/pytype/pytd/pytd_visitors.py#L281) to detect empty tuples and write them as `Tuple[()]` in the pyi file. If that doesn't work out, another possibility would be to teach merge_pyi that when it reads in `Tuple[nothing, ...]`, it should output `Tuple[()]`.

Thanks for the help :)

**Comment by souravbadami** [comment]
@rchen152 - Should we output `Tuple[()]` or `Tuple[...]`?

As I see we emit Ellipsis at most of the places throughout the codebase.

**Comment by rchen152** [comment]
I'd go with `Tuple[()]` in order to follow PEP 484 (https://www.python.org/dev/peps/pep-0484/#the-typing-module). The other type are harder to handle, since as far as I know, there's no official way to type an empty list, dict, etc. Maybe we should go with rewriting the annotations in merge_pyi rather than trying to change PrintVisitor. If we do that, then we can just change `nothing` to `Any` for the non-`Tuple` types. (We wouldn't want to do that in PrintVisitor, since it could negatively affect downstream inference.)

**Comment by Cebtenzzre** [comment]
It seems like this was not completely fixed - the "nothing" type can still leak out:
```python
i = 1
x, = (i,) + ()
reveal_type(x)
```
```
File "/home/cebtenzzre/repr.py", line 3, in <module>: Union[int, nothing] [reveal-type]
```
