### ISSUE TITLE
set up a build system for pytype binary wheels

### ISSUE THREAD

**Issue by rchen152** [google/pytype#562]
since pytype's source installation depends on a c compiler, it would be nice to have binary wheels uploaded to pypi. this requires building the wheel on the target machine. we need each of
* manylinux (docker images available)
* windows (need a vm with a c compiler and toolchain)
* mac (???)

**Comment by IaroslavR** [comment]
It can be done with the help of https://github.com/pypa/auditwheel I done some researches in https://github.com/IaroslavR/aws-lambda-builder and except of one problem - https://github.com/pypa/auditwheel/issues/159 it's a pretty straightforward  process

**Comment by bsolomon1124** [comment]
I am interested in helping out with this and have some experience building platform wheels in other projects.  GitHub Actions, Travis, and Azure DO all have support for Windows and MacOSX, I believe.

**Comment by bsolomon1124** [comment]
Some notes from Mac OS X 10.15.4 below.

Sequence of commands used to build macosx wheel:

```
$ git clone --recurse-submodules https://github.com/google/pytype.git
$ cd pytype
$ pyenv local 3.8.3
$ python -m venv venv
$ . ./venv/bin/activate
$ python -m pip install -U pip wheel setuptools
$ CMAKE_PREFIX_PATH="$(brew --prefix bison)" python setup.py bdist_wheel
$ ls dist/*.whl
dist/pytype-2020.5.13-cp38-cp38-macosx_10_15_x86_64.whl
```

Notes on the dependencies from https://github.com/google/pytype/blob/master/CONTRIBUTING.md#pytype-dependencies:

**A C++11 compiler for your platform**: Mac OS X masks `g++` to `clang`.  (It's not a symlink; I'm actually not sure what it is, but...)

```
$ g++ --help | head -n3
OVERVIEW: clang LLVM compiler

USAGE: clang [options] file...
```

Also, I'm not sure if `/usr/bin/g++` exists out of the box or needs `xcode-select --install` to be put there.

**CMake version 2.8 or higher**:

This one is easy, `brew install -v cmake`.

**Bison version 3.0.2 or higher**: 

This one is a bit tricky because in my case I had `/usr/bin/bison` version 2.3.  (Again, not sure if this was from `xcode` or there already.)

So after using `brew install -v bison`, which is "keg-only", I needed the `CMAKE_PREFIX_PATH` to tell CMake where to find Bison version 3.x.

**Flex version 2.5.35 or higher**: Same as above here; `flex 2.5.35 Apple(flex-32)` sits at /usr/bin/flex, but not sure if that is a result of `xcode-select --install`.  This is why I sorely need a Mac OS Docker image :(

**Python2.7 and Python3.x Interpreters**: For build only, I used Python 3.8.3 as shown above.

**Comment by rchen152** [comment]
Thanks so much for looking into this! Let me know if you run into any questions/difficulty on https://github.com/google/pytype/pull/593.

The state of Travis's macOS support looks odd. https://docs.travis-ci.com/user/languages/python/ says right at the top that macOS is unsupported, but a little further down, https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems provides instructions for running Python tests on macOS :woman_shrugging:

**Comment by rchen152** [comment]
pytype 2020.07.14 has manylinux and macOS wheels. I was able to install the manylinux wheel on my linux machine, and we have one user report of a successful installation of the macOS python3.6 wheel. I'm going to go ahead and close this issue, since Windows is not supported.

Thanks to @bsolomon1124 for figuring out how to build these wheels!
