### ISSUE TITLE
Coordinate CONTRIBUTING.md and our new dev docs

### ISSUE THREAD

**Issue by rchen152** [google/pytype#570]
The in-progress dev docs have a section on developer workflow: https://google.github.io/pytype/developers/index.html. We also have https://github.com/google/pytype/blob/master/CONTRIBUTING.md. They read like standalone docs with no knowledge of each other and contain different, occasionally overlapping (but at least not contradicting, I think) information. We should coordinate them in some way so it's clear which one(s) a contributor should read.

**Comment by dipscodehub** [comment]
Hello @rchen152 can you please let me know if this Issue is still open and needs to be completed.
I'm new to open source contribution so it would be great if you can guide me through the steps to complete tasks.

**Comment by rchen152** [comment]
Hello! Thank you for your interest in contributing to pytype. Unfortunately, this isn't a good first-time issue, since it requires one to be fairly familiar with pytype's code base and development workflow. If you let me know what kind of topic/challenge you're interested in, I can try to suggest some issues that are more contributor-friendly.

**Comment by dipscodehub** [comment]
@rchen152  actually I'm familiar with python and javascript but I don't have anyone to guide me regarding where to start and how to get started.
It would be great if you guide me and mentor me regarding this.

@rchen152  can i have your linkedin so that you can tell me more about open source contribution as typing here again and again would turn this into spam.

**Comment by martindemello** [comment]
Hi @dipscodehub , please don't worry about spam, we welcome open discussions on our github page since they are often to other people later on. In particular here, since our developer docs are meant to make it easier for newcomers to start contributing, it would be very relevant to figure out how they can best be structured and what would help you decide how and where to start.

Areas to contribute to pytype are broadly
* type inference and checking - this is pytype's core functionality, and unfortunately can be pretty hard to get up to speed on if you are not already familiar with types in general, and a bit of python internals (in particular bytecode and the class/object system, and the way code is executed in the interpreter).
* platform specific issues - since all the pytype developers use linux, we have some open windows and macos issues that we could definitely use help on
* python ecosystem and infrastructure - we could always use help integrating pytype better into the python ecosystem, including things like binary wheels, integration with popular test frameworks and IDEs.

Do any of these sound interesting to you?

**Comment by dipscodehub** [comment]
@martindemello thank you for the help.
As I'm a beginner to this field of open source contribution so i should start from the very basic I guess. I've a deep knowledge of python and it's core modules. So can you please help me selecting some good issues i can start with. 
I would be really grateful to you if you help me in my first stage of open source contribution.

**Comment by martindemello** [comment]
@dipscodehub if I may ask, are you specifically interested in pytype, or just in getting involved with python open source? pytype unfortunately is a pretty thorny project to get into as your first open source contribution, because it depends heavily on knowledge not just of python and its core modules, but on the implementation of the python interpreter itself. Also the project internals are not well documented; we are working on that but even when we are done we will have to assume that the reader is familiar with a lot of language implementation details, including [the cpython code](https://github.com/python/cpython), a bit of the theory behind gradual typing and object oriented type systems, interpreter data structures like code frames, abstract syntax trees, and control flow graphs, and techniques like parsing and constraint solving.

If you do have a background, or deep interest, in language implementation and tooling, and if [PEP484](https://www.python.org/dev/peps/pep-0484/) sounds like an interesting part of the python ecosystem, you might still find pytype a rewarding project to be involved in, but with only three developers I'm afraid we won't be able to provide much in the way of mentorship other than helping you find your way around the codebase and engaging in discussions of the open issues.

If you don't have the background, but are specifically looking to learn about and get involved in PEP484-based type checking, [mypy](http://mypy-lang.org/) might be a better option - not only is the code and contribution process better documented, but they have widespread community adoption and are as close to an "official" type checker as exists in the python world.

If you are just interested in contributing to the python open source ecosystem, my advice would be to first think of any particular interests you have (e.g. web development, game programming, machine learning, etc) and then to see what the python projects in that area are. (And if you let us know what areas you are interested in we can help with suggestions; one of python's major strengths is that it has a ton of libraries for practically any application you can think of.)

**Comment by dipscodehub** [comment]
@martindemello thanks a ton for your great advice. You're really awesome.
As you've told pytype is a thorny project to start with and would require a lot of knowledge to begin with.
Can you please advice me some good Projects for beginners to start with in the field of JavaScript or Python. 
In JavaScript currently I'm working with react and I use Python for solving problems.
So can you please suggest me some good project to start with, also can I have your LinkedIn Id so that whenever i get stuck I can get back to you.

**Comment by martindemello** [comment]
@dipscodehub I'm afraid I don't have much time to provide ongoing help, but I can give you some advice to get started. Firstly, I feel like you are approaching this wrong - no one can just tell you what projects you might find interesting to work on, it needs to have some relation to your own individual tastes and background. Ideal would be if it's some project you actually use and are enthusiastic about, or a project that relates to some other hobby or interest of yours.

After that, you need to put in some work to get up and running on your own, using the project's documentation as a guide. Open source is mostly run by volunteers, most of whom will not have the time or energy to help people who have a bare "can you suggest what I should work on, and then how to do it" request. However, if you actually dive in, get the project checked out and set up, start to work on a feature, and then find out that you are blocked because the documentation is inadequate, or because something worked in an unexpected manner, you can submit a very focused request for help, and people will be happy to get you unstuck. 

If your primary goal is to get involved in open source, I would start by spending some time reading through freecodecamp's  [really good collection of guides to contributing to open source](https://github.com/freeCodeCamp/how-to-contribute-to-open-source). You will notice that even though that page has a ton of helpful resources, they do not address the issue of which project exactly you should pick to contribute to - just things to look for that would make a project suitable, like issues tagged "for beginners only".

If you do want to work on a popular open source app with a lot of users and good documentation for how to contribute, you can check out [zulip](https://zulip.readthedocs.io/en/latest/overview/contributing.html) as an example - I am not suggesting that that is the best project for you because I do not know what sort of projects you will enjoy working on, but they are a great example of a project that uses both python and javascript, and has done the work to identify beginner-friendly issues and write up detailed guidelines on getting up and running. And again, if you do decide that that is a project you would like to work on, I strongly recommend trying to get everything set up and experiment with making some small change on your own before asking for help.

**Comment by dipscodehub** [comment]
@martindemello Thanks a Ton.
Thank you for your genuine advice and the help.
I know you are busy most of the time and would not be able to help or reply but can i have your linkedin id so that If i get stuck at some point I can get some good advice from you.
anyways thank you for your support and help. 😊

**Comment by martindemello** [comment]
@dipscodehub I would rather not give that out randomly, but also if you go through all the freecodecamp links on that page, I'm pretty sure you won't get stuck with anything! It's a really good collection of advice written by people with far more experience than me.
