### ISSUE TITLE
incorrectly flagged [attribute-error] for telnetlib.Telnet

### ISSUE THREAD

**Issue by abhishek-pandey** [google/pytype#590]
test.py [Python 3.6.8 & pytype==2020.5.13]
```
from telnetlib import Telnet

session = Telnet("host", 1234)
print (session.host)
```

Output of running pytype:

> $ pytype test.py
> Computing dependencies
> Analyzing 1 sources with 0 local dependencies
> ninja: Entering directory `/home/xxx/.pytype'
> [1/1] check test
> FAILED: /home/xxx/.pytype/pyi/test.pyi 
> /home/xxx/bin/python -m pytype.single --imports_info /home/xxx/.pytype/imports/test.imports --module-name test -V 3.6 -o /home/xxx/.pytype/pyi/test.pyi --analyze-annotated --nofail --quick /home/xxx/test.py
> File "/home/xxx/test.py", line 4, in <module>: **No attribute 'host' on telnetlib.Telnet [attribute-error]**
> 
> For more details, see https://google.github.io/pytype/errors.html#attribute-error.
> ninja: build stopped: subcommand failed.
> $ 
>

**Comment by rchen152** [comment]
Appears to be because Telnet has no `host` attribute here: https://github.com/python/typeshed/blob/1f7023b95787bc86e8f867843ac90f70ed8f6049/stdlib/2and3/telnetlib.pyi#L86. The docs make no mention of this attribute (https://docs.python.org/3/library/telnetlib.html), but you can add it along with an `# undocumented` comment to the stub.

Let me see if I can transfer this issue directly to the typeshed repo, haven't tried this before.

**Comment by rchen152** [comment]
Ah, looks like I can only transfer issues to repositories that I'm an admin for.

**Comment by hauntsaninja** [comment]
I think you can't transfer issues across Github organisations/users

**Comment by rchen152** [comment]
> I think you can't transfer issues across Github organisations/users

That makes sense, thanks.

Closing this issue since the attribute has been added to typeshed.
