### ISSUE TITLE
Add support for NewType in stubs

### ISSUE THREAD

**Issue by CraftSpider** [google/pytype#597]
Currently, pytype emits a syntax error on NewType in stubs. As a minimal example:

```py
_Type = NewType('_T', int)
```
Results in `ParseError: syntax error, unexpected '(', expecting DEF`

**Comment by rchen152** [comment]
Sorry for the slow response. To support this, I suppose we'd have to add a NEWTYPE token, like what we did with NamedTuple: https://github.com/google/pytype/blob/3610c139d522056b0f40c3bee74c4e3369a0bbaf/pytype/pyi/parser_ext.cc#L294. It's a little annoying to implement because then NewType basically becomes a keyword, so we'd have to add a case for it to import parsing, etc.
