### ISSUE TITLE
Wrong handling of defaultdict since 2020.06.26

### ISSUE THREAD

**Issue by MatthiasThul** [google/pytype#615]
```python
from collections import defaultdict
from typing import Dict


def f(x: int) -> str:
    return str(x)                                                                                                                                                                                             

d: Dict[int, str] = defaultdict(default_factory=f)
```

With pytype 2020.06.01 I get no errors. With 2020.06.26, I get

```bash
File "test.py", line 8, in <module>: Type annotation for d does not match type of assignment [annotation-type-mismatch]
  Annotation: Dict[int, str]
  Assignment: collections.defaultdict[str, Callable[[int], str]]

For more details, see https://google.github.io/pytype/errors.html#annotation-type-mismatch.
ninja: build stopped: subcommand failed.
```

**Comment by rchen152** [comment]
The latest release didn't change pytype's handling of defaultdict, but it did include a partial fix for https://github.com/google/pytype/issues/323. (We're rolling the fix out in stages because it affects a lot of Google code.) Before, the annotation on `d` was not being type-checked against the value, and now it is.

As far as I can tell, pytype is correct here. The default_factory argument to defaultdict can only be passed in as a positional argument; `defaultfactory(default_factory=f)` creates a dictionary with one key, 'default_factory', whose value is a `Callable[[int], str]]`.

On a side note, the default factory should not take any arguments: https://docs.python.org/3/library/collections.html#defaultdict-objects.

**Comment by MatthiasThul** [comment]
You're absolutely right - my bad. Thank you.
