### ISSUE TITLE
Inference on metaclasses

### ISSUE THREAD

**Issue by colin-grapl** [google/pytype#623]
Something I've noticed with pytype is that it can generate a type definition for a metaclass only if there is a static string passed into `type`.

As an example
```
class A(object):
  def foo(self):
    print('foo')

class B(object):
  def bar(self):
    print('bar')

def combine_types(a: Type[A], b: Type[B]):  # Properly generates C and is inferred as return type
    x = type('C', (a, b), {})
    return x

C = combine_types(A, B)
```
This all type checks just fine.

However, if we change it to this:

```
def combine_types(type_name: str, a: Type[A], b: Type[B]):  # Infers return as Any
    x = type(type_name, (a, b), {})
    return x

C = combine_types('C', A, B)
```
The inferred type is Any
What won't type check properly (the return type is Any).

The generated pyi for the latter looks like this:

```
class A:
    def foo(self) -> None: ...

class B:
    def bar(self) -> None: ...

class C(A, B): ...

def combine_types(type_name: str, a: Type[A], b: Type[B]) -> Any: ...
```

Clearly pytype can understand that C needs to exist, but it can't propagate that type 'out' of the combine_types.

I'm not really an expert on metaclasses or anything, so I apologize if my terminology is off. Hopefully this is clear enough.

**Comment by rchen152** [comment]
Is the top-level definition of `C` supposed to use `combine_types` rather than `type`?

**Comment by colin-grapl** [comment]
Hi, I've updated my post to fix that issue.

**Comment by rchen152** [comment]
Thanks, I understand the problem now. What's going on is that because of the annotation on `type_name`, pytype replaces the literal "C" string with a generic instance of `str` when analyzing `combine_types`. If `combine_types` is only ever used in the same file, you should be able to fix this by removing the annotation:
```
def combine_types(type_name, a: Type[A], b: Type[B]): ...
```
The inferred return type will still be `Any`, but `C` will have the right type. If you need to use `combine_types` in another file, then I'm afraid I don't know a way to annotate this function to precisely express what it's doing.

**Comment by colin-grapl** [comment]
Oh, interesting. That works for me. I can make that work for my use case fairly easily. Thank you.

**Comment by rchen152** [comment]
Glad that worked!
