### ISSUE TITLE
pytype does not pring 'leaving directory' - affects emacs

### ISSUE THREAD

**Issue by alex4747-pub** [google/pytype#659]
Pytype prints "entering directory" but does not print "leaving directory" - it screws up emacs compilation-search-path
It is minor but annoying, please fix

pytype --config=pytype.cfg *.py
Computing dependencies
Analyzing 5 sources with 0 local dependencies
ninja: Entering directory `/home/ar/volta-cli-work/volta-cli/pycli/.pytype'
[1/2] check schema_tree
[2/2] check main
Success: no errors found

**Comment by rchen152** [comment]
Spent more time than I should've poking around the ninja github project. (ninja is the build system that we farm out pytype-single invocations to.) Looks like ninja intentionally uses the "entering directory" language because emacs recognizes it, which works well when running ninja directly because it actually cd's into the directory in question.

For pytype, the directory doesn't actually change when ninja claims it does (I guess because we're calling it via subprocess?), leading to this issue.

Seems we should probably just also print "Leaving directory xxx", since suppressing the ninja output would cause the "[n/m] check xxx" progress messages to be lost.

**Comment by alex4747-pub** [comment]
Thank you, I suppose printing 'leaving directory' will be enough.
