### ISSUE TITLE
[QUESTION] Running Pytype on Projects that are under development

### ISSUE THREAD

**Issue by maldil** [google/pytype#667]
Hello, 

I have a question regarding the capabilities of using `pytypes` on changing source codes.
I have a couple of independent projects that contain thousands of lines of codes. It takes a significant amount of time `pytype` to finish the type analysis of each project. 
I know that `pytype` internally builds a type graph when It infers the type information of internal variables. Let's assume that I perform a small edit on a project (when I perform an edit on `version-1`, code becomes  `version-2` after the edit). **What are the capabilities that I can use?, Or what techniques that `pytype` already use to reduce the processing time when inferring types of the new version source code (`version-2`)?.** The best approach is to infer type only on the changed elements and the impacted code elements.

For example:
`version-1`
File name = boo.py
```
def boo()
     return 1
```

File name = foo.py
```
import boo
def foo()
    return boo.boo()
```
`version-2` - I changed only the return type of `def boo()` as below. 
File name = boo.py
```
def boo()
     return "boo"
```

I changed the return type of `def boo()` in `boo.py` to `string` from `int` in `version-2`. This source code had thousands of unchanged code beside the code edit as I have shown above. It is obvious that we can re-analyse only the changed code elements and the impacted codes in order to reduce analysis time. **Does `pytype` support this? Or what are the workarounds that I can use to reduce the processing time?**

Thank you in advance.

**Comment by rchen152** [comment]
Unfortunately, pytype does not have the capability to partially re-analyze a file: if anything changes, it needs to re-analyze the entire file. Some tips we generally give users who are struggling with long analysis times are:

* If possible, the best way to speed up pytype is to split up large files. Anecdotally, pytype is noticeably slower once a file grows past ~1500 lines.
* Having lots of Union annotations can slow down pytype by causing the number of possible combinations of types to quickly explode.
* Large concrete data structures (e.g., a module-level dict of a hundred constants) can be problematic because pytype tracks individual values for some builtin data structures, which quickly gets unwieldy.
