### ISSUE TITLE
Variable type comment after one-line function parsed as function type comment

### ISSUE THREAD

**Issue by Cebtenzzre** [google/pytype#683]
pytype gave me a confusing error. The minimal working example is more complex than I expected.

#### Example Code
```python
def foo(): pass

x = 0  # type: int

def bar():
    """docstring"""
```
#### Actual Behavior
```
$ pytype-single repr.py
File "repr.py", line 3, in <module>: Invalid function type comment: int [invalid-function-type-comment]

For more details, see https://google.github.io/pytype/errors.html#invalid-function-type-comment.
```

Scope and other definitions don't change this - you can put any of the three definitions in a class, nest either of the functions in another function, or add more variables or functions between them. All that seems to matter is the presence and order of the three definitions.

#### Expected Behavior
This code is correct, so pytype shouldn't complain. The only unusual thing about it is the one-line definition of `foo`.

#### Software Versions
pytype master (2020.9.16)
Python 3.7 (also tested 3.8)

**Comment by rchen152** [comment]
Ha, this is an amusing bug. Seems to be caused by this code: https://github.com/google/pytype/blob/2f2a1483751171421490c352f05955655ea572fa/pytype/blocks.py#L400
Since `foo` is a single-line function, we check whether it has a docstring, in order to get the full range of lines in which a function type comment for `foo` is allowed to appear. But the docstring check does not have an upper bound (despite my clear attempt to add one using `max_line`), so we mistakenly associate `bar`'s docstring with `foo` and treat `# type: int` as being a function type comment for `foo`.

Thanks for creating a minimal example! It made debugging much easier.

**Comment by Cebtenzzre** [comment]
To be completely accurate, the second function doesn't necessarily have to be docstring-only to trigger the bug, it can be any function with a docstring. Either way, the latest pytype runs fine on the problematic codebase now, thanks!
