### ISSUE TITLE
Casting away `Optional`

### ISSUE THREAD

**Issue by MatthiasThul** [google/pytype#752]
(See https://github.com/python/typing/issues/645 for a related discussion.)

Consider the following file `test.py`:

```python
from typing import TypeVar, Optional

T = TypeVar('T')

def cast_away_optional(x: Optional[T]) -> T:
    assert x is not None
    return x

def foo(i: int) -> Optional[int]:
    if i == 42:
        return i
    return None

x = foo(1)
reveal_type(x)

y = cast_away_optional(x)
reveal_type(y)

assert x is not None
reveal_type(x)
```

PyType `2020.12.2` gives:

```bash
File "/Users/someone/code/pytype/test.py", line 15, in <module>: Optional[int] [reveal-type]
File "/Users/someone/code/pytype/test.py", line 18, in <module>: Optional[int] [reveal-type]
File "/Users/someone/code/pytype/test.py", line 21, in <module>: int [reveal-type]
```

It is surprising to me that `y` is not inferred as `int` while `x` at the end is.

Mypy `0.790` gives as expected:

```bash
test.py:15: note: Revealed type is 'Union[builtins.int, None]'
test.py:18: note: Revealed type is 'builtins.int*'
test.py:21: note: Revealed type is 'builtins.int'
```

**Comment by rchen152** [comment]
Seems to be a bug in our union matching (https://github.com/google/pytype/blob/22545931decb6e14a63e1ed66c81899c9277203b/pytype/matcher.py#L331). In matching against `Optional[T]`, once a value matches `None`, we should return a successful match, rather than going on and matching the value to `T` as well.
