### ISSUE TITLE
Can't find pyi for module involved in circular import

### ISSUE THREAD

**Issue by leon-vv** [google/pytype#760]
Hi, thanks for this great project!

I think the error I'm running into is the same #320 and #355  but I am not 100% sure. In any case, it's related to a circular import which pytype fails to follow correctly.

Here is a small program illustrating the isssue:

```Python
# This is A.py
from B import Y

class X:
    def __init__(self):
        self.y = Y(self)

x = X()
```

```Python
# This is B.py
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from A import X

class Y:
    def __init__(self, x: 'X'):
        self.x = x
```
So basically, X and Y both have a reference to each other. Running `pytype ./*.py` produces

```
File "/home/leonvv/Development/Python/pytype-test/B.py", line 4, in <module>:
   Couldn't import pyi for 'A' [pyi-error]
       Can't find pyi for 'B', referenced from 'A'
```

**Comment by rchen152** [comment]
This is an interesting bug! It's caused by this block of code:

https://github.com/google/pytype/blob/25eb59fb5414849636c49700b8e22d3cece752ab/pytype/imports_map_loader.py#L75-L85

Because of the circular import, B.py is analyzed twice. The second time, the pyi generated by the first analysis is discarded from the imports map, causing the pyi error. The tricky part is figuring out how to stop discarding the pyi without triggering the bug that the discard works around, which is that if you use the pyi file generated from the first-pass analysis of a module's `__init__.py` file as an input to the second pass, then any submodules that were analyzed after `__init__.py` are looked up as Any.

One idea is to modify [vm._import_module](https://github.com/google/pytype/blob/25eb59fb5414849636c49700b8e22d3cece752ab/pytype/vm.py#L1574) so that when `foo/__init__` imports `foo`, we return an empty module. This assumes that there's no way for `foo/__init__` to indirectly reference itself - imports that go through the loader would still pick up the pyi file. What concerns me is that if I accidentally reintroduce the submodule lookup bug, it'll be hard to detect because it's likely that nothing will break - instead, things will silently pass type-checking that shouldn't. This'll probably take some time to test properly.
