### ISSUE TITLE
Tuple[()] is wrongly compatible with Tuple[Any, Any]

### ISSUE THREAD

**Issue by mrahtz** [google/pytype#767]
When a function is annotated as taking an empty tuple, a call to the function with a non-empty tuple is caught as expected:

`foomain.py`:
```python
from typing import Any, Tuple

def f(x: Tuple[()]):
  return None

f((Any, Any))
```

```
$ pytype foomain.py
File "/tmp/foomain.py", line 6, in <module>: Function f was called with the wrong arguments [wrong-arg-types]
         Expected: (x: Tuple[()])
  Actually passed: (x: Tuple[Any, Any])
```

But if the function is defined in a separate file, pytype *doesn't* catch the error:

`foomain.py`:
```python
from typing import Any
import foolib

foolib.f((Any, Any))
```

`foolib.py`:
```python
from typing import Tuple

def f(x: Tuple[()]):
  return None
```

```
$ pytype foomain.py
Success: no errors found
```

Tested with pytype 2020.12.16.

Thanks!

**Comment by rchen152** [comment]
Seems to be caused by the pyi parser special-casing empty tuples: https://github.com/google/pytype/blob/b3bc4080dab60de625b2de31b0d73de1c46bc5b7/pytype/pyi/parser.py#L839. If it's possible to remove the special case, that would probably be the easiest fix; otherwise, we'll need some code in convert.py to identify empty tuples.

**Comment by mrahtz** [comment]
Awesome, thanks! 😁
