### ISSUE TITLE
Faced Issue installing pytype in Ubuntu 16

### ISSUE THREAD

**Issue by Satyabhama-Reddy** [google/pytype#826]
`
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/user/.local/lib/python3.7/site-packages/pybind11/include -I/usr/include/python3.7m -c pytype/typegraph/reachable.cc -o build/temp.linux-x86_64-3.7/pytype/typegraph/reachable.o -fvisibility=hidden -g0 -std=c++11
    In file included from pytype/typegraph/reachable.cc:1:0:
    pytype/typegraph/reachable.h:19:3: error: ‘size_t’ does not name a type
       size_t size() const { return size_; }
       ^
    pytype/typegraph/reachable.h:23:3: error: ‘size_t’ does not name a type
       size_t num_nodes_;  // == adj_.size() == adj_[0].size()
       ^
    pytype/typegraph/reachable.h:24:3: error: ‘size_t’ does not name a type
       size_t size_;
       ^
    pytype/typegraph/reachable.cc: In constructor ‘devtools_python_typegraph::ReachabilityAnalyzer::ReachabilityAnalyzer()’:
    pytype/typegraph/reachable.cc:11:48: error: class ‘devtools_python_typegraph::ReachabilityAnalyzer’ does not have any field named ‘num_nodes_’
     ReachabilityAnalyzer::ReachabilityAnalyzer() : num_nodes_(0) {
                                                    ^
    pytype/typegraph/reachable.cc: In member function ‘int devtools_python_typegraph::ReachabilityAnalyzer::add_node()’:
    pytype/typegraph/reachable.cc:16:14: error: ‘num_nodes_’ was not declared in this scope
       int node = num_nodes_++;
                  ^
    pytype/typegraph/reachable.cc:17:3: error: ‘size_’ was not declared in this scope
       size_ = (num_nodes_ + 63) / 64;
       ^
    pytype/typegraph/reachable.cc: In member function ‘void devtools_python_typegraph::ReachabilityAnalyzer::add_connection(int, int)’:
    pytype/typegraph/reachable.cc:33:23: error: ‘num_nodes_’ was not declared in this scope
       for (int i = 0; i < num_nodes_; i++) {
                           ^
    pytype/typegraph/reachable.cc:37:27: error: ‘size_’ was not declared in this scope
           for (int j = 0; j < size_; j++) {
                               ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

It worked after I changed size_t to std::size_t
gcc version : gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 
What could the issue be?

**Comment by rchen152** [comment]
Could you provide a bit more detail? What command did you run that produced this error message? (`pip install pytype`?) Where in the code did you change `size_t` to `std::size_t` to work around it?

**Comment by Satyabhama-Reddy** [comment]
I first tried `pip install pytype` and got this error, then I downloaded the code and tried with `pip install . `, which gave the same error.

Made the `size_t` to `std::size_t` change in the following lines:
https://github.com/google/pytype/blob/fc96224fd3923433bdfca63592d57406abb792a3/pytype/typegraph/reachable.h#L19
https://github.com/google/pytype/blob/fc96224fd3923433bdfca63592d57406abb792a3/pytype/typegraph/reachable.h#L23
https://github.com/google/pytype/blob/fc96224fd3923433bdfca63592d57406abb792a3/pytype/typegraph/reachable.h#L24

**Comment by rchen152** [comment]
Thanks for the additional information! Seems like we might as well change `size_t` to `std::size_t` in reachable.h, since that doesn't break anything as far as I can tell, but I'm trying to understand why these particular references to `size_t` are problematic when `size_t` is used all over the place in typegraph/.

**Comment by Solumin** [comment]
This will be fixed in the next pytype release.

`size_t` is defined in a number of header files, though `<cstddef>` is the most minimal of these. The C++11 standard guarantees that `cstddef` will define `size_t` in the `std` namespace (e.g. `std::size_t`), but some implementations also define it in the global namespace for backwards compatibility. It seems that the C++ headers we use differ from those in Ubuntu 16 in this way.

The reason this was caught in reachable.h is that file only includes `cstdint`, which is not guaranteed to define `size_t`. There's a chance we would have run into this in the other typegraph/ files, since they import `cstddef` but do not qualify `size_t`.

**Comment by rchen152** [comment]
Thanks to @Solumin for fixing this in https://github.com/google/pytype/commit/7661b7c47a5f061d11103a73f5115fd1896abebc. If nothing unexpected comes up, the next pytype release will be later this week.
